config/routes.rb
CrowdCourse::Application.routes.draw do

  get "comments/new"

  resources :s3_uploads

  get "search/index"

  root :to => 'dynamic_pages#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", 
                                    :registrations => "registrations"}

  match 'courses/:id/settings' => 'courses#info_settings'
  match 'courses/:id/settings/info' => 'courses#info_settings'
  match 'courses/:id/settings/contributors' => 'courses#contributors_settings'
  match 'courses/:id/settings/maintainers' => 'courses#maintainers_settings'
  match 'courses/:id/settings/syllabus' => 'courses#syllabus_settings'

  match '/profile' => 'users#show', :as => 'profile'
  match 'my_courses' => 'users#courses'

  match 'privacy_settings' => 'users#privacy_settings'
  match 'update_user_privacy_settings' => 'users#update_privacy'
  match 'donation_settings' => 'users#donation_settings'
  match 'update_user_donation_settings' => 'users#update_donation_settings'

  match '/style-tests' => 'static_pages#styleTests'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/legal' => 'static_pages#legal'
  match '/guidelines' => 'static_pages#community_guidelines'
  match '/video_guidelines' => 'static_pages#video_guidelines'
  match '/news' => 'static_pages#news'

  match '/home' => 'dynamic_pages#home'
  match '/landing' => 'dynamic_pages#landing'
  match '/learn' => 'dynamic_pages#learn'
  match '/teach' => 'dynamic_pages#teach'

  match '/search' => 'search#index'

  match '/check_answer/:question_id/:value' => 'quizzes#check_answer'
  match '/quizzes/:id/get_questions' => 'quizzes#get_questions'
  match '/quizzes/:id/complete/:score' => 'quizzes#complete_quiz'
  match '/video_view_complete' => 'videos#video_view_complete'
  match '/video_view' => 'videos#video_view'
  match '/rate_video' => 'videos#rate'
  match 'destroy_component' => 'components#destroy'
  match 'change_section' => 'components#change_section'
  match 'destroy_section' => 'sections#destroy'
  match 'destroy_course_with_confirmation' => 'courses#destroy_with_confirmation'
  match 'add_maintainer' => 'courses#add_maintainer'
  match 'destroy_choice' => 'quiz_choices#destroy'

  match 'users/update_description' => 'users#update_description'
  match 'mailing_list_members/create' => 'mailing_list_members#create'
  match 'videos/create_from_url' => 'videos#create_from_url'
  match 'videos/create_from_file' => 'videos#create_from_file'

  resources :categories, only: [:show, :index]
  resources :courses
  resources :sections, except: [:index]
  resources :components, except: [:index] do
    collection { post :sort }
  end

  resources :videos, except: [:update, :edit]
  resources :comments
  resources :quizzes
  resources :field_questions, except: [:index, :show]
  resources :choice_questions, except: [:index, :show]
  resources :quiz_choices, except: [:index, :show]

  resources :users, only: [:show, :update]

  resources :mailing_list_members, only: [:new, :create]

  match '/robots.txt' => 'application#robots'

  

  match '/teapot' => 'application#teapot'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def styleTests
	end

	def about
	end

	def contact
	end

	def legal
	end

	def community_guidelines
	end

	def video_guidelines
	end

	def news
		@mailing_list_member = MailingListMember.new
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_math_markup_test.html.erb
<div class="markup-test-container">
	<div class="markup-text-area">
		<textarea class="markup-text" rows="8" placeholder="Enter some math stuff in between two backticks ( ` ) and click render."></textarea>
		<button class="btn btn-large" id="render-button">Render</button>
		<button class="btn btn-large" id="example-button">Show Example</button>
	</div>
	<div class="markup-result">
		Results will show up here.
	</div>

	<script>
			$("#render-button").click(function() {
				$(".markup-result").html($(".markup-text").val());
				MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
			})

			$("#example-button").click(function() {
				$(".markup-text").val("`x = (-b +- sqrt(b^2 - 4ac)) / (2a)`");
				$(".markup-result").html($(".markup-text").val());
				MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
			})
	</script>
	<div class="clear"></div>
</div>

app/views/static_pages/_privacy_policy.html.erb
<h3>1. We collect personal and activity data, which may be linked.</h3>

<p>
  We use technologies like cookies (small files stored on your browser), web beacons,
  or unique device identifiers to identify your computer or device so we can deliver
  a better experience. Our systems also log information like your browser, operating
  system and IP address.
</p>

<p>
  We also may collect personally identifiable information that you provide to us, such 
  as your name, address, phone number or email address. With your permission, we may 
  also access other personal information on your device, such as your phone book, 
  calendar or messages, in order to provide services to you. If authorized by you, 
  we may also access profile and other information from services like Facebook.
</p>

<p>
  Our systems may associate this personal information with your activities in the course of providing service to you (such as pages you view or things you click on or search for).
</p>

<p>
  We do not knowingly contact or collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us so we can promptly obtain parental consent or remove the information.
</p>

<br/>



<h3>2. We do not store or share your precise location.</h3>

<p>
  We do not use or collect your precise geographic location.
</p>

<br/>



<h3>3. You can request to see your personal data.</h3>

<p>
  You can sign into your account to see any personally identifiable information we have stored, such as your name, email, address or phone number. You can also contact us by email to request to see this information.
</p>

<br/>



<h3>4. We keep personal data until you delete it.</h3>

<p>
  We remove personally identifiable information (such as your name, address, email or phone number) and other preferences associated with your account promptly after you delete your account. We may retain other data indefinitely.
</p>

<br/>



<h3>5. We don't share your personal data with other companies.</h3>

<p>
  We generally do not share personally identifiable information (such as name, address, email or phone) with other companies.
</p>

<br/>



<h3>6. No ad companies collect data through our service.</h3>

<p>
  We do not allow advertising companies to collect data through our service for ad targeting.
</p>

<br/>



<h3>7. Service providers access data on our behalf.</h3>

<p>
  In order to serve you, we may share your personal and anonymous information with other companies, including vendors and contractors. Their use of information is limited to these purposes, and subject to agreements that require them to keep the information confidential. Our vendors provide assurance that they take reasonable steps to safeguard the data they hold on our behalf, although data security cannot be guaranteed.
</p>

<p>
  Analytics companies may access anonymous data (such as your IP address or device ID) to help us understand how our services are used. They use this data solely on our behalf. They do not share it except in aggregate form; no data is shared as to any individual user. Click to see company privacy policies that govern their use of data.
</p>

<p>Google Analytics</p>

<p>
  Google Analytics is a web analytics tool that helps website owners understand how visitors engage with their website. Google Analytics customers can view a variety of reports about how visitors interact with their website so they can improve it. Google Analytics collects information anonymously. It reports website trends without identifying individual visitors.
</p>

<p>
  <a target="_blank" href="http://www.google.com/intl/en/policies/privacy/">Google Analytics Privacy Policy</a>
</p>

<br/>



<h3>8. We take steps to protect personal information.</h3>

<p>
  We take reasonable steps to secure your personally identifiable information against unauthorized access or disclosure. We encrypt transmission of data on pages where you provide payment information. However, no security or encryption method can be guaranteed to protect information from hackers or human error.
</p>

<p>
  Information we collect may be stored or processed on computers located in any country where we do business.
</p>

<br/>



<h3>9. You can ask privacy questions.</h3>

<p>
  If you have any questions or concerns about our privacy policies, please contact us:
  <br/> 
  <div class="legal-contact-info">
    <p>
      <%= mail_to "legal@crowdcourse.com" %> (preferred)
    </p>
    <p>
      CrowdCourse Headquarters<br/>
      205 Alexander Ave. Apt. D<br/>
      Durham, NC 27705<br/>
    </p>
  </div>

</p>

<br/>



<h3>10. Special situations may require disclosure of your data.</h3>

<p>
  To operate the service, we also may make identifiable and anonymous information available to third parties in these limited circumstances: (1) with your express consent, (2) when we have a good faith belief it is required by law, (3) when we have a good faith belief it is necessary to protect our rights or property, or (4) to any successor or purchaser in a merger, acquisition, liquidation, dissolution or sale of assets. Your consent will not be required for disclosure in these cases, but we will attempt to notify you, to the extent permitted by law to do so.
</p>

<br/>



<h3>11. You can review more privacy-related information.</h3>

<p>
  This privacy policy was last updated on July 1, 2012. Our privacy policy may change from time to time. If we make any material changes to our policies, we will place a prominent notice on our website or application. If the change materially affects registered users, we will send a notice to you by email, push notification or text.
</p>

<br/><br/>

<p>
  <b>Last Updated: July 1, 2012</b>
</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:active, 'About') %>

<!-- Facebook like button code.. -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=119367024876251";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="row bottom-space-more top-space">
	<div class="about-content bottom-space-most span12 grey-box more-padding">
		<div class="holder">
			<div class="row-fluid bottom-space">
				<div class="span12">
				<h1 class="large inline">About CrowdCourse</h1>
				<div class="fb-like inline left-space" data-href="http://facebook.com/crowdcourse" 
								data-send="false" data-width="360" data-show-faces="false">
				</div>
					<br/><br/>
					<p style="font-size: 20px; line-height: 28px;">
						CrowdCourse is a community-driven educational website. It was founded by a college
						student, and focuses on helping you learn quickly and effectively. We're brand new, but
						we're pleased to offer a lot of great resources and features. Scroll down to find out
						more!
					</p>
				</div>

				<div class="clear"></div>
			</div>

			<hr/>
			
			<div class="row-fluid bottom-space-more" id="learn-from-community-row">

				<div class="span6 learn-from-community-image">
					<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/classroom.png" %>
				</div>

				<div class="span6 top-space-more blue-accent" id="learn-from-community-text">
					<h1>Join Our Community</h1>
					<br/>
					<p>
						CrowdCourse is powered by a community of teachers, professors, and students.
						<strong>Anyone can help!</strong> If you're passionate about teaching, 
						you can contribute by uploading a video, submitting
						a question, or organizing lesson plans and syllabi. 
					</p>
				</div>

				<div class="clear"></div>

			</div>

			<div class="row-fluid bottom-space-most" id="learn-faster-row">

				<div class="span6 top-space-more green-accent" id="learn-faster-text" >
					<h1>Learn Faster</h1>
					<br/>
					<p>
						The lessons on CrowdCourse are <strong> short and to the point</strong>.
						So instead of sitting through a long lecture, you can cut through the fluff, 
						find exactly what you're looking for, and
						<strong>learn faster than ever</strong>.
					</p>
					<p>
						<%= link_to "See a sample course", "courses/1" %>
					</p>
				</div>

				<div class="span6" id="learn-faster-image">
					<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/course.png" %>
				</div>

				<div class="clear"></div>

			</div>

			<hr/>

			<div class="row-fluid top-space bottom-space-more center">
				<br/>
				<h1 class="large">
					Watch High Quality Videos
				</h1>
				<br/>
				<br/>
				<span>
					<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/devices.png" %>
				</span>
			</div>

			<div class="row-fluid bottom-space-most">
				<div class="span4 purple-accent">
					<h2>
						<i class="icon-film"></i>
						Short and Sweet
					</h2>
					<p>
						Most of the videos on CrowdCourse are less than 5 minutes long, so you can
						learn fast and keep moving forward.
					</p>
					<p>
						<%= link_to "See a sample video", "videos/12" %>
					</p>
				</div>

				<div class="span4 blue-accent">
					<h2>
						<i class="icon-globe"></i>
						Mobile-Friendly
					</h2>
					<p>
						Watch videos on any desktop or mobile device, including iPhone,
						iPad, Android, Windows Phone, and more!
					</p>
					<p>
						<%= link_to "See a sample video", "videos/12" %>
					</p>
				</div>

				<div class="span4 green-accent">
					<h2>
						<i class="icon-eye-open"></i>
						High Definition
					</h2>
					<p>
						The videos on CrowdCourse are in beautiful HD quality, and they stream lightning
						fast through our html5 player.
					</p>
					<p>
						<%= link_to "See a sample video", "videos/12" %>
					</p>
				</div>

				<div class="clear"></div>
			</div>

			<hr/>

			<div class="row-fluid top-space bottom-space-more center">
				<br/>
				<h1 class="large">
					Take Interactive Quizzes
				</h1>
				<br/>
				<br/>
				<div class="center quiz-image-container"
					<span>
						<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/quizzes.png" %>
					</span>
				</div>
			</div>

			<div class="row-fluid bottom-space-more">
				<div class="span6 green-accent">
					<h2>
						<i class="icon-ok"></i>
						Immediate Feedback
					</h2>
					<p>
						Tired of waiting for weeks to get back graded homework assignments?
						With CrowdCourse, you can take an interactive quiz to <strong>immediately</strong> check your
						understanding.
					</p>
					<p>
						<%= link_to "See a sample quiz", "quizzes/4" %>
					</p>
				</div>
				<div class="span6 purple-accent">
					<h2>
						<i class="icon-tasks"></i>
						A Variety of Questions
					</h2>
					<p>
						Our quizzes feature a <strong>variety of question formats</strong>, both multiple choice
						and free response. With CrowdCourse, you'll always be prepared.
					</p>
					<p>
						<%= link_to "See a sample quiz", "quizzes/4" %>
					</p>
				</div>

				<div class="clear"></div>
			</div>

			<hr/>

			<div class="row-fluid bottom-space-more top-space">
				<div class="span6">
					<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/rewards.png" %>
				</div>
				<div class="span6 top-space-most blue-accent">
					<h1>Earn Rewards</h1>
					<p>
						You can <strong>earn points and badges</strong> every time you 
						watch a video, take a quiz, post a comment, and more! You can earn 
						even more rewards by contributing content, such as uploading a video. 
					</p>
					<p>
						<strong>Each week, we will congratulate the users with the most points by
						featuring them on our homepage!</strong>
					</p>
				</div>

				<div class="clear"></div>
			</div>

			<div class="row-fluid bottom-space-more">
				<div class="span6 top-space-more green-accent">
					<h1>Find it Fast</h1>
					<p>
						CrowdCourse features an <strong>intelligent semantic search</strong>, so you 
						can find what you're looking for faster. You can even use natural language
						and mathematical symbols.
					</p>
					<p>
						<%= link_to "Search for something", search_path %>
					</p>
				</div>
				<div class="span6">
					<%= image_tag "http://dl9f4gn4hf44p.cloudfront.net/images/search.png" %>
				</div>

				<div class="clear"></div>
			</div>

			<hr/>

			<div class="row-fluid bottom-space-more top-space-most center">
				<h1 class="large">What are you waiting for?</h1>
				<br/><br/>
				<p>
					<%= link_to user_omniauth_authorize_path(:facebook), :class => "btn btn-large btn-facebook" do %>
						<i class="icon-facebook icon-large"></i>
					  &nbsp;&nbsp;Sign up with Facebook
					<% end %>
					&nbsp;<strong>or</strong>&nbsp;
					<%= link_to new_user_registration_path, :class => "btn btn-large btn-blue" do %>
						<i class="icon-envelope-alt icon-large"></i>
					  &nbsp;&nbsp;Sign up with Email
					<% end %>
				</p>

				<br/><br/>

				<p class="center">
					You might also want to check out our 
					<%= link_to "News and Announcements", news_path %> page
				</p>
			</div>

		</div>		
	</div>
</div>

app/views/static_pages/community_guidelines.html.erb
<% provide(:title, 'Community Guidelines') %>

<div class="hero-unit">
	<h1>Community Guidelines</h1>
</div>

<div class="guidelines-container">
	<div class="row">
		<div class="grey-box span12">
			<p class= "guidelines-intro">
				<h1>A Foreword</h1>
				<br/>
				We strongly believe that anyone can teach, be they professors, teachers, TA's students,
				or just people passionate about education. Similarly, we believe that anyone can learn
				if provided with the right tools. We are happy to open our doors to everyone, and it is 
				our goal to connect teachers and learners to facilitate a community where better education
				thrives. You are considered a member of the CrowdCourse community if you watch a video,
				create an account, upload a video, post a comment, or otherwise participate in the website
				in any way. As a member of our community, we ask that you please adhere to the guidelines
				listed below. In general, all we ask is that you use common sense and be respectful of others.
			</p>

			<br/>
			<hr/>
			<br/>
			
			<h3>1. All content you contribute must be your own work.</h3>	

			<p>
				Any content you contribute (be it a video, a comment, or any other contribution to the website),
				must be your own work. If the content is copyrighted, you must be either the holder of the
				copyright or have express permission from the holder of the copyright to display the content
				on our site.
			</p>

			<br/>

			<h3>2. Commercial content of any kind is not allowed.</h3>

			<p>
				Prohibited commercial content includes any material submitted to the website which:
				<ul>
					<li>
						is or contains advertisements of any kind
					</li>
					<li>
						promotes a business
					</li>
					<li>
						promotes a competing or similar website
					</li>
					<li>
						is created for the main purpose of generating revenue
					</li>
				</ul>
			</p>

			<br/>

			<h3>3. Hateful or hurtful language is not allowed.</h3>

			<p>
				Prohibited language includes:
				<ul>
					<li>
						profanity or swearing
					</li>
					<li>
						threats or personal insults
					</li>
					<li>
						derogatory speech towards a certain ethnicity, religion, class, or other demographic
					</li>
				</ul>
			</p>
			<p>
				Please note that you <b><i>are</i></b> allowed to give negative feedback.
				In fact, honest feedback is an important part of what makes the CrowdCourse 
				community so great. Just keep in mind that your feedback should always 
				be respectful, constructive, and non-personal.
			</p>

			<br/>

			<h3>4. No nudity, pornography, or sexually explicit content.</h3>

			<p>
				You must not upload any videos which are pornographic or sexual in nature. Nudity
				of any kind is not allowed. Comments which are sexually suggestive, or which might
				be considered sexual harassment are strictly prohibited.
			</p>

			<br/>

			<h3>5. Other prohibited content</h3>

			<p>
				In addition to what's listed above, you may not contribute any content that:
				<ul>
					<li>
						exhibits drug abuse
					</li>
					<li>
						shows extreme violence (including animal abuse)
					</li>
					<li>
						shows or suggests any type of illegal act
					</li>
					<li>
						might be considered shocking or disgusting
					</li>
					<li>
						violates the privacy or rights of another individual
					</li>
					<li>
						intentionally misleads students/learners by teaching content incorrectly
					</li>
					<li>
						is automatically or randomly generated
					</li>
					<li>
						includes an impersonation of another individual (such as a professor)
					</li>
				</ul>
			</p>

		</div>
	</div>

<div class="row">
		<div class="grey-box span12 vertical-space-more">
			<p class= "guidelines-outro">
				As compliant with our <%= link_to "Terms of Service", "/legal#terms" %>, CrowdCourse reserves
				the right to <b><i>remove any content</i></b> that does not adhere the the above guidelines, at 
				CrowdCourse's sole discretion. We also reserve the right to <b><i>restrict the access of</i></b>, or 
				<b><i>permanently delete</i></b> the CrowdCourse accounts of repeat offenders, or offenders who have 
				caused extensive or grave consequences by violating the above guidelines, as determined at our sole 
				discretion. We hope that we will never need to exercise these rights.
			</p>
		</div>
	</div>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="hero-unit contact-content">
	<h1>Contact</h1>
	<p>
		We'd love to hear what you have to say, whether it's suggestions, bug reports, or just appreciation.
		You can contact us at any of the following email addresses, depending on the nature of your message:
	</p>

	<p>
		<ul>
			<li>
				For feedback or course suggestions: <%= mail_to "feedback@crowdcourse.com" %>
			</li>
			<li>
				For technical support or bug reports: <%= mail_to "support@crowdcourse.com" %>
			</li>
			<li>
				For legal concerns or questions about our policies: <%= mail_to "legal@crowdcourse.com" %>
			</li>
			<li>
				For all other purposes: <%= mail_to "contact@crowdcourse.com" %>
			</li>
		</ul>
	</p>

</div>

app/views/static_pages/legal.html.erb
<% provide(:title, 'Legal') %>
<% provide(:active, 'Legal') %>

<div class="row">
	<div class="span12 grey-box more-padding bottom-space-more center">
		<h1 class="large">Legal Stuff</h1>
		<%= link_to "Privacy Policy", "#privacy", :class => "smooth-scroll" %> 
		&nbsp; | &nbsp;
		<%= link_to "Terms of Service", "#terms", :class => "smooth-scroll" %>
	</div>
</div>

<div class="row">
	<div class="grey-box span12 privacy-container more-padding" id="privacy" name="privacy">
		<h1><%= link_to "Privacy Policy", "#privacy", :class => "smooth-scroll link-grey" %></h1>
		<hr/>
		<%= render '/static_pages/privacy_policy' %>
	</div>
</div>

<div class="row">
	<div class="grey-box span12 vertical-space-more terms-container more-padding" id="terms" name="terms">
		<h1><%= link_to "Terms of Service", "#terms", :class => "smooth-scroll link-grey" %></h1>
		<hr/>
		<%= render '/static_pages/terms' %>
	</div>
</div>

app/views/static_pages/video_guidelines.html.erb
<div class="hero-unit vertical-space video-guidelines">
	<h1>Video Quality Guidelines</h1>
	<br/>
	<p>
	In addition to following our <%= link_to "Community Guidelines", guidelines_path %>, we ask that people who upload videos follow these general rules to ensure quality. It is our mission to offer the best learning experience possible to our users, and we reserve the right to remove any videos that do not adhere to the following guidelines.		
	</p>
	<br/>
	<p>
		<ul>
			<li>
				Videos must address the lesson under which they are uploaded. It is okay
				to mention preceeding or proceeding lessons, but going into detail
				about them is not allowed.
			</li>
			<li> 
				Videos should be short and to the point. Don't ramble on about 
				things that are irrelevant to the topic at hand.
			</li>
			<li>
				Excessive intros and outros are not allowed. Short ones are okay though.
			</li>
			<li>
				Do not play music in your videos. The majority of viewers 
				will find this annoying.
			</li>
			<li>
				Ensure that videos are taken in good lighting and that any
				text is legible.
			</li>
			<li>
				Similarly, make sure that any speech in the video is loud enough
				to hear and easy to understand.
			</li>
		</ul>
	</p>
	<br/>
	<br/>
	<p>
		Thanks for your interest in contributing to CrowdCourse!
	</p>
</div>