config/routes.rb
CrowdCourse::Application.routes.draw do

  get "comments/new"

  resources :s3_uploads

  get "search/index"

  root :to => 'dynamic_pages#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", 
                                    :registrations => "registrations"}

  match 'courses/:id/settings' => 'courses#info_settings'
  match 'courses/:id/settings/info' => 'courses#info_settings'
  match 'courses/:id/settings/contributors' => 'courses#contributors_settings'
  match 'courses/:id/settings/maintainers' => 'courses#maintainers_settings'
  match 'courses/:id/settings/syllabus' => 'courses#syllabus_settings'

  match '/profile' => 'users#show', :as => 'profile'
  match 'my_courses' => 'users#courses'

  match 'privacy_settings' => 'users#privacy_settings'
  match 'update_user_privacy_settings' => 'users#update_privacy'
  match 'donation_settings' => 'users#donation_settings'
  match 'update_user_donation_settings' => 'users#update_donation_settings'

  match '/style-tests' => 'static_pages#styleTests'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/legal' => 'static_pages#legal'
  match '/guidelines' => 'static_pages#community_guidelines'
  match '/video_guidelines' => 'static_pages#video_guidelines'
  match '/news' => 'static_pages#news'

  match '/home' => 'dynamic_pages#home'
  match '/landing' => 'dynamic_pages#landing'
  match '/learn' => 'dynamic_pages#learn'
  match '/teach' => 'dynamic_pages#teach'

  match '/search' => 'search#index'

  match '/check_answer/:question_id/:value' => 'quizzes#check_answer'
  match '/quizzes/:id/get_questions' => 'quizzes#get_questions'
  match '/quizzes/:id/complete/:score' => 'quizzes#complete_quiz'
  match '/video_view_complete' => 'videos#video_view_complete'
  match '/video_view' => 'videos#video_view'
  match '/rate_video' => 'videos#rate'
  match 'destroy_component' => 'components#destroy'
  match 'change_section' => 'components#change_section'
  match 'destroy_section' => 'sections#destroy'
  match 'destroy_course_with_confirmation' => 'courses#destroy_with_confirmation'
  match 'add_maintainer' => 'courses#add_maintainer'
  match 'destroy_choice' => 'quiz_choices#destroy'

  match 'users/update_description' => 'users#update_description'
  match 'mailing_list_members/create' => 'mailing_list_members#create'
  match 'videos/create_from_url' => 'videos#create_from_url'
  match 'videos/create_from_file' => 'videos#create_from_file'

  resources :categories, only: [:show, :index]
  resources :courses
  resources :sections, except: [:index]
  resources :components, except: [:index] do
    collection { post :sort }
  end

  resources :videos, except: [:update, :edit]
  resources :comments
  resources :quizzes
  resources :field_questions, except: [:index, :show]
  resources :choice_questions, except: [:index, :show]
  resources :quiz_choices, except: [:index, :show]

  resources :users, only: [:show, :update]

  resources :mailing_list_members, only: [:new, :create]

  match '/robots.txt' => 'application#robots'

  

  match '/teapot' => 'application#teapot'

end

app/views/settings/_settings_nav.html.erb
<div class="span3 grey-box">
	<h2>Settings</h2>
	
	<div class="holder">
		<div class="row-fluid">
			<div class="span12">
				<ul class="nav nav-pills nav-stacked colored-nav">
				  	
		  		<li <%= "class='active'" if active == :account %> >
		  			<%= link_to "Account", edit_user_registration_path %>
		  		</li>

				 	<li <%= "class='active'" if active == :privacy %> >
						<%= link_to "Privacy", privacy_settings_path %>
				  </li>

				  <li <%= "class='active'" if active == :donation %> >
						<%= link_to "Donations", donation_settings_path %>
				  </li>

				</ul>
			</div>
		</div>
	</div>
</div>

app/views/settings/donation_settings.html.erb
<%= provide(:title, 'Donations Settings') %>

<!-- This view may or may not be used in the settings menu... -->

<div class="row">

  <%= render 'settings/settings_nav', :active => :donation %>

  <div class="span9 grey-box">
    <h2>Donations</h2>
    <br/>
    
    <h3>Coming Soon!</h3>

    <p class="medium">
      Soon, you will have the option to accept donations. These donations will
      go straight to you and CrowdCourse will not take a cut. This is only available
      for users who have submitted original content.
    </p>

    <%#  
    <p class="medium">
      If you've contributed original content to CrowdCourse, you will be able to 
      accept donations. Users will be able to click a donate button on your profile
      and choose the amount they wish to donate. CrowdCourse does not take a cut, and
      100% of the proceeds go dircetly to you (minus paypal fees, if applicable).
    </p>
    <p class="medium">
      <strong>If the contributed content is copyrighted or licensed, you must ensure
      that the acceptance of donations does not violate the copyright or lisence terms.
      </strong>
    </p>
    <p class="medium">
      Check the box
      below if you want to accept donations.
    </p>
    <br/>
    %>
    
    <%# form_for @user, :url => update_user_donation_settings_path do |f| %>
      
      <%# <p class="medium left-space"> %>

        <%# f.check_box :accept_donations, :value => @user.accept_donations? %>
        <%# f.label :accept_donations, :class => "inline" %>
       <%#  <br/><br/>
      </p> %>

      <%# f.submit "Update Settings", :class => "btn btn-blue btn-large" %>
    <%# end %>

    

  </div>
</div>

app/views/settings/privacy_settings.html.erb
<%= provide(:title, 'Privacy Settings') %>

<div class="row">

  <%= render 'settings/settings_nav', :active => :privacy %>

  <div class="span9 grey-box">
  <h2>Privacy</h2>
  <br/>
  <h3>Choose what will appear on your <%= link_to "profile", profile_path %>:</h3>
  <br/>

    <%= form_for @user, :url => update_user_privacy_settings_path do |f| %>
      
      <p class="medium left-space">

        <%= f.check_box :show_stats, :value => @user.show_stats? %>
        <%= f.label :show_stats, :class => "inline" %>
        <br/><br/>

        <%= f.check_box :show_activity, :value => @user.show_activity? %>
        <%= f.label :show_activity, :class => "inline" %>
        <br/><br/>

        <%= f.check_box :show_videos_made, :value => @user.show_videos_made? %>
        <%= f.label :show_videos_made, :class => "inline" %>
        <br/><br/>

        <%= f.check_box :show_full_name, :value => @user.show_full_name? %>
        <%= f.label :show_full_name, :class => "inline" %>
        <br/><br/>

        <%= f.check_box :show_email, :value => @user.show_email? %>
        <%= f.label :show_email, :class => "inline" %>
        <br/><br/>
      </p>

      <%= f.submit "Update Settings", :class => "btn btn-blue btn-large" %>
    <% end %>

  </div>
</div>