config/routes.rb
CrowdCourse::Application.routes.draw do

  get "comments/new"

  resources :s3_uploads

  get "search/index"

  root :to => 'dynamic_pages#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", 
                                    :registrations => "registrations"}

  match 'courses/:id/settings' => 'courses#info_settings'
  match 'courses/:id/settings/info' => 'courses#info_settings'
  match 'courses/:id/settings/contributors' => 'courses#contributors_settings'
  match 'courses/:id/settings/maintainers' => 'courses#maintainers_settings'
  match 'courses/:id/settings/syllabus' => 'courses#syllabus_settings'

  match '/profile' => 'users#show', :as => 'profile'
  match 'my_courses' => 'users#courses'

  match 'privacy_settings' => 'users#privacy_settings'
  match 'update_user_privacy_settings' => 'users#update_privacy'
  match 'donation_settings' => 'users#donation_settings'
  match 'update_user_donation_settings' => 'users#update_donation_settings'

  match '/style-tests' => 'static_pages#styleTests'
  match '/about' => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  match '/legal' => 'static_pages#legal'
  match '/guidelines' => 'static_pages#community_guidelines'
  match '/video_guidelines' => 'static_pages#video_guidelines'
  match '/news' => 'static_pages#news'

  match '/home' => 'dynamic_pages#home'
  match '/landing' => 'dynamic_pages#landing'
  match '/learn' => 'dynamic_pages#learn'
  match '/teach' => 'dynamic_pages#teach'

  match '/search' => 'search#index'

  match '/check_answer/:question_id/:value' => 'quizzes#check_answer'
  match '/quizzes/:id/get_questions' => 'quizzes#get_questions'
  match '/quizzes/:id/complete/:score' => 'quizzes#complete_quiz'
  match '/video_view_complete' => 'videos#video_view_complete'
  match '/video_view' => 'videos#video_view'
  match '/rate_video' => 'videos#rate'
  match 'destroy_component' => 'components#destroy'
  match 'change_section' => 'components#change_section'
  match 'destroy_section' => 'sections#destroy'
  match 'destroy_course_with_confirmation' => 'courses#destroy_with_confirmation'
  match 'add_maintainer' => 'courses#add_maintainer'
  match 'destroy_choice' => 'quiz_choices#destroy'

  match 'users/update_description' => 'users#update_description'
  match 'mailing_list_members/create' => 'mailing_list_members#create'
  match 'videos/create_from_url' => 'videos#create_from_url'
  match 'videos/create_from_file' => 'videos#create_from_file'

  resources :categories, only: [:show, :index]
  resources :courses
  resources :sections, except: [:index]
  resources :components, except: [:index] do
    collection { post :sort }
  end

  resources :videos, except: [:update, :edit]
  resources :comments
  resources :quizzes
  resources :field_questions, except: [:index, :show]
  resources :choice_questions, except: [:index, :show]
  resources :quiz_choices, except: [:index, :show]

  resources :users, only: [:show, :update]

  resources :mailing_list_members, only: [:new, :create]

  match '/robots.txt' => 'application#robots'

  

  match '/teapot' => 'application#teapot'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_filter :authenticate_user!, :except => [:index, :show]

	def index
		@courses = Course.all
		if !@courses.empty?

			## 
			# We need to search through each course to find out which categories are present.
			# The following code retrieves a set of categories for which there are courses in the search results
			# There is only one occurence of each category
			# This way we can sort the search results by category.

			@categories = @courses.inject(@courses.first.categories) {|result, course| result = result | course.categories}

		else
			@categories = []
		end
	end

	def show
		@course = Course.find_by_id(params[:id])
		if @course.nil?
			flash[:blue] = "That course does not exist or has been removed!"
			redirect_to root_path
			return
		end
		@term = params[:search]
  	# @components = Component.search(@term, @course) TODO: fix search
  	@components = @course.components.prioritized
  	@sections = @course.sections.prioritized
  	@show_admin_options = @course.maintainers.include? current_user
  end

  def new
  	@course ||= Course.new
  	@category ||= Category.new
  	@category_options = category_options_for (c = @course)
  end

  def create

  	@course = Course.new params[:course]

		##
		# the params include the category_id of an existing category.
		# if the user elects to create a new category, the 
		# category_id is -1, which means find_by_id will be nil
		@category = Category.find_by_id(params[:category_id])
		if !@category
			@category = Category.create :name => params[:category_name]
		end

		if !@category.valid?
			error_during_create
			return
		end

		@course.save
		if !@course.valid?
			error_during_create
			return
		end
		@course.categories << @category

		##
		# if there is no priority provided, we have to 
		# set one. The default is simply to place the new
		# course after the last course in the category...
		if params[:course][:priority].blank?
			max_priority = @category.courses.maximum("priority")
			@course.priority = max_priority ? max_priority + 1 : 1
		end

		@course.maintainers << current_user

		@course.save
		redirect_to @course
	end

	def update

		@course = Course.find_by_id(params[:id])
		authenticate_as_maintainer @course

		##
		# the params include the category_id of an existing category.
		# if the user elects to create a new category, the 
		# category_id is -1, which means find_by_id will be nil
		@category = Category.find_by_id(params[:category_id])
		if !@category
			@category = Category.create :name => params[:category_name]
		end

		if !@category.valid?
			error_during_update
			return
		end

		@course.update_attributes params[:course]
		if !@course.valid?
			error_during_update
			return
		end
		@course.categories.clear
		@course.categories << @category
		@course.save

		##
		# if there is no priority provided, we have to 
		# set one. The default is simply to place the new
		# course after the last course in the category...
		if params[:course][:priority].blank?
			max_priority = @category.courses.maximum("priority")
			@course.priority = max_priority ? max_priority + 1 : 1
		end

		@category_options = category_options_for (c = @course)
		@selected_category = @course.categories.first.id

		redirect_to @course.info_settings_path
	end

	def info_settings
		@course = Course.find(params[:id])
		authenticate_as_maintainer @course
		@category = @course.categories.first
		@category_options = category_options_for (c = @course)
		@selected_category = @course.categories.first.id
	end

	def syllabus_settings
		@course = Course.find(params[:id])
		authenticate_as_maintainer @course
	end

	def contributors_settings
		@course = Course.find(params[:id])
		authenticate_as_maintainer @course
	end

	def maintainers_settings
		@course = Course.find(params[:id])
		authenticate_as_maintainer @course
		require 'json'
		@usernames = User.all_usernames.to_json
	end

	def destroy_with_confirmation
		@course = Course.find(params[:course_id])
		authenticate_as_maintainer @course
		if @course.name == params[:course_confirm_name]
			@course.destroy
			flash[:blue] = "The course has been destroyed."
			redirect_to root_path
			return
		else
			flash[:blue] = "The course name you entered did not match. Please try again."
			redirect_to @course.info_settings_path
			return
		end
	end

	def add_maintainer
		@course = Course.find(params[:course_id])
		authenticate_as_maintainer @course
		if params[:username].blank?
			flash[:blue] = "Please enter a valid username and then press \"add\""
			redirect_to @course.maintainers_settings_path
			return
		end
		@user = User.find_by_username(params[:username])
		if @user.nil?
			flash[:blue] = "The username #{params[:username]} does not exist. Did you make a typo?"
			redirect_to @course.maintainers_settings_path
			return
		elsif @course.maintainers.include? @user
			flash[:blue] = "#{@user.username} is already a maintainer for this course!"
			redirect_to @course.maintainers_settings_path
			return
		else
			@course.maintainers << @user
			flash[:blue] = "#{@user.username} has been added as a maintainer!"
			redirect_to @course.maintainers_settings_path
			return
		end
	end

	private

	def authenticate_as_maintainer(course)
		unless course.maintainers.include? current_user
			flash[:blue] = "You don't have permission to do that!"
			redirect_to course
			return
		end
	end

	def category_options_for (c = @course)
		options = Array.new
		Category.all.collect do |cat| 
			options << [cat.name, cat.id]
		end
		options << ["Create new Category", -1]
	end

	def error_during_create
		@course ||= Course.new
		@category ||= Category.new
		@category_options = category_options_for (c = @course)
		if !@course.categories.empty?
			@selected_category = @course.categories.first.id
		end
		flash[:blue] = "There were some problems with the information you submitted (see below for details)."
		render 'courses/new'
	end

	def error_during_update
		@course ||= Course.find_by_id(params[:id])
		@category ||= @course.category
		@category_options = category_options_for (c = @course)
		if !@course.categories.empty?
			@selected_category = @course.categories.first.id
		end
		flash[:blue] = "There were some problems with the information you submitted (see below for details)."
		render 'courses/info_settings'
	end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<% accent_color ||= :blue %>

<div class="list-item course-item grey-box span6 <%= accent_color %>-accent">
	<h3><%= link_to course.name, course %></h3>
	<div class="course-description">
		<%= truncate course.description.html_safe, :length => 150 %>
		<nobr><%= link_to "See More", course %></nobr>
	</div>
	<div class="course-lesson-count pull-right"><%= pluralize(course.components.count, "Lesson") %></div>
</div>

app/views/courses/_coursemap.html.erb
<%# The coursemap renders a shortlist of the sections and lessons in a given course. %>
<%# It requires a single local variable, :course %>

<div class="holder">
	<div class="row-fluid">
		<div class="coursemap span12 white-box">
		<h2 class="inline">Course Overview</h2>&nbsp;&nbsp;(scroll down to see details)
		<% course.sections.prioritized.each do |sec| %>
			<% condensed_name = sec.name.downcase.gsub(" ", "_").gsub("'", "") # remove spaces and unusual chars %>

			<div class="coursemap-section">

			<h4>
				<%# fuck yeah! my custom to_roman method (and a nifty Romanizable module) defined in custom_initializer.rb %> 
				<%= link_to "#{sec.priority.to_roman}. #{sec.name}", "##{condensed_name}", :class => "link-grey no-underline smooth-scroll" %>
			</h4>
			
				<ul>

				<% sec.components.prioritized.each_slice(3) do |slice| %>

				<%# renders an unordered list, with two items on each row %>
				<%# here, each slice contains 3 components %>

					<div class="threesome">
						<div class="coursemap-item">
							<li>
								<%= link_to slice[0].name, slice[0], :class => "no-underline" %>
							</li>
						</div>
						<% if slice[1] # sometimes the slice will only contain 1 element if it's at the end %> 
							<div class="coursemap-item">
								<li>
									<%= link_to slice[1].name, slice[1], :class => "no-underline" %>
								</li>
							</div>
						<% end %>
						<% if slice[2] # sometimes the slice will only contain 1 element if it's at the end %> 
							<div class="coursemap-item">
								<li>
									<%= link_to slice[2].name, slice[2], :class => "no-underline" %>
								</li>
							</div>
						<% end %>
					</div>
				<% end %>
				</ul>
				<div class="clear"></div>
			</div>

		<% end %>
		<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>

app/views/courses/_settings_nav.html.erb
<div class="span4 grey-box">
	<h2>Course Settings</h2>
	<h3 class="lighten"><%= link_to @course.name, @course, :class => "link-light-grey" %></h3>
	
	<div class="holder">
		<div class="row-fluid top-space">
			<div class="span12">
				<ul class="nav nav-pills nav-stacked colored-nav">
				  	
		  		<li <%= "class='active'" if active == :basic_info %> >
		  			<%= link_to "Basic Info", @course.info_settings_path %>
		  		</li>

		  		<li <%= "class='active'" if active == :syllabus %> >
						<%= link_to "Syllabus", @course.syllabus_settings_path %>
		  		</li>

					
					<!-- Hide for now (not ready yet) -->
				 	<!-- <li <%= "class='active'" if active == :contributors %> >
						<%= link_to "Contributors", @course.contributors_settings_path %>
				  </li> -->

				  <li <%= "class='active'" if active == :maintainers %> >
						<%= link_to "Maintainers", @course.maintainers_settings_path %>
				  </li>

				</ul>
			</div>
		</div>
	</div>
</div>

app/views/courses/contributors_settings.html.erb
<% provide(:title, "Settings for #{@course.name}") %>

<div class="row">
	
	<%= render 'courses/settings_nav', :active => :contributors %>

	<div class="span8 grey-box">
		<h2>Contributors</h2>

		<%=  %>
		
	</div>
</div>

app/views/courses/index.html.erb
<% provide(:title, 'Courses') %>

<div class="hero-unit">
	<h1>All Courses</h1>
	
	<p>
		All of our courses are managed by a small group of maintainers, and anyone can contribute. 
		Click on a course to find out more information or start taking lessons.
	</p>
	<br/>
	<p>
		Got an idea for a course that isn't listed here?
	</p>
	<p>
		<%= link_to new_course_path, :class=> "btn btn-large btn-blue" do %>
			<i class="icon icon-plus"></i>
			Start a New Course
		<% end %>
	</p>
	
	
</div>

<%= render 'lists/sectioned_list', :sections => @categories, :sections_have_own_page => true %>

app/views/courses/info_settings.html.erb
<% provide(:title, "Settings for #{@course.name}") %>

<div class="row">
	
	<%= render 'courses/settings_nav', :active => :basic_info %>

	<div class="span8 grey-box">
		<h2>Basic Info</h2>

		<% if @course.errors.any? || @category.errors.any? %>
			<div class="alert alert-white">
				<button class="close" data-dismiss="alert">&times;</button>
				<h3>There were some errors:</h3>
				<ul>
				<% @course.errors.full_messages.each do |msg| %>
					<li>
						Course <%= msg %>
					</li>
				<% end %>
				<% @category.errors.full_messages.each do |msg| %>
					<li>
						Category <%= msg %>
					</li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<%= form_for @course do |f| %>
			
			<div class="medium">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>

			
			<div class="medium">
				<%= label_tag "Category" %>
				<%= select_tag(:category_id, 

					options_for_select(
							@category_options, @selected_category
					),

				:class => "category_id_select") %>
			</div>

			<div class="category_text_field hide">
				<div class="medium">
					<%= label_tag :category_name %>
					<%= text_field_tag :category_name %>
				</div>
			</div>

			<br/>

			<div class="medium">
				<%= f.label :description %>
				<%= f.text_area :description, :rows => 8 %>
			</div>

			
			<%= f.submit "Update Course", :class => "btn btn-large btn-blue" %>

		<% end %>

		<br/>
		<hr/>
		<br/>
		<h2 class="color-purple">Danger Zone</h2>
		<%= form_tag destroy_course_with_confirmation_path do %>
			
			<p>
				<div class="alert alert-purple">
					<strong>
						To delete this course forever, type in the full course
						name below and press the delete button. All the sections,
						lessons, videos, and quizzes associated with this course
						will also be deleted.
					</strong>
				</div>
			</p>

			<%= hidden_field_tag :course_id, @course.id  %>

			<p class="medium">
				<%= label_tag :course_confirm_name %>
				<%= text_field_tag :course_confirm_name %>
			</p>

			<%= submit_tag "Delete Course", :class => "btn btn-large btn-purple",
			:confirm => "Are you sure you want to delete the course entitled #{@course.name}? This cannot be undone." %>

		<% end %>
	</div>
</div>

app/views/courses/maintainers_settings.html.erb
<% provide(:title, "Settings for #{@course.name}") %>

<div class="row">
	
	<%= render 'courses/settings_nav', :active => :maintainers %>

	<div class="span8 grey-box">
		<h2>Maintainers</h2>
		<%= render 'lists/inline_list', :items => @course.maintainers, 
											:prioritized => false, :bg_color => :white %>

		<hr/>

		<%= form_tag add_maintainer_path do %>
			
			<p>
				To add another maintainer, start typing a username in the field below.
			</p>

			<%= hidden_field_tag :course_id, @course.id  %>

			<%= text_field_tag :username, "", 
						'data-provide' => 'typeahead', 'data-source' => @usernames,
						:class => "span6 inline" %>

			<%= submit_tag "Add", :class => "btn btn-large btn-blue",
					:confirm => "Are you sure you want to make this user a maintainer? (Cannot undo)." %>

		<% end %>
	</div>
</div>

app/views/courses/new.html.erb
<% provide(:title, "New Course") %>

<div class="row">
	<div class="span12 grey-box more-padding">
		<h1 class="large">Start a Course</h1>
		<br/>
		<p class="medium">
			<strong>Note:</strong> Before you get started, please check if the course you want to start has already been started by
			another member. For example, we only want one Introductory Calculus Course, so that it's easier
			for prospective learners to find what they're looking for and compare available resources. You can
			use the search bar in the top right corner to search all of our existing courses.
		</p>
		<p class="medium">
			By creating this course, you will automatically become the first maintainer. You will be in charge of
			moderating the content that other people submit for the course. You may also choose other maintainers
			to help you with this responsibility. 
		</p>
		<br/>

		<% if @course.errors.any? || @category.errors.any? %>
			<div class="alert alert-white">
				<button class="close" data-dismiss="alert">&times;</button>
				<h3>There were some errors:</h3>
				<ul>
				<% @course.errors.full_messages.each do |msg| %>
					<li>
						Course <%= msg %>
					</li>
				<% end %>
				<% @category.errors.full_messages.each do |msg| %>
					<li>
						Category <%= msg %>
					</li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<%= form_for @course do |f| %>
			
			<div class="medium">
				<%= f.label :name, "Course Name" %>
				<%= f.text_field :name %>
			</div>

			
			<div class="medium">
				<%= label_tag "Category" %>
				<%= select_tag :category_id,
						options_for_select(@category_options),
						:class => "category_id_select" %>
			</div>

			<div class="category_text_field hide">
				<div class="medium">
					<%= label_tag :category_name %>
					<%= text_field_tag :category_name %>
				</div>
			</div>

			<br/>

			<div class="medium">
				<%= f.label :description %>
				<%= f.text_area :description, :rows => 8 %>
			</div>

			
			<%= f.submit "Start Course", :class => "btn btn-large btn-blue" %>

		<% end %>
	</div>
</div>

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>

<% crumbs = [{ :name => "All Courses", :path => courses_path }] 
		crumbs << { :name => @course.categories.first.name, :path => @course.categories.first }
		crumbs << { :name => @course.name, :path => nil } 
%>

<%= render 'shared/breadcrumbs', :crumbs => crumbs %>

<div class="hero-unit botom-space-most">
	<h1 class="inline"><%= @course.name %></h1>
	<p>
		<%= @course.description.html_safe %>
	</p>

	<% if @show_admin_options %>
		<span class="blue-accent">
			<%= link_to @course.info_settings_path, :class => "no-underline" do %>
				<h2 class="inline">
					<i class="icon icon-cog"></i>
					Settings
				</h2>
			<% end %>
		</span>
	<% end %>

	<% if !@course.sections.blank? %>
		<div class="coursemap-container top-space-most">
			<%= render 'courses/coursemap', :course => @course %>
		</div>
	<% else %>
		<% if @show_admin_options %>
			<br/>
			<br/>
			<p>
			<div class="well white-well center">
				<p>
					Thank you for contributing to CrowdCourse!
					<br/>
					This course still needs a syllabus.
					<br/><br/>
					<%= link_to "Create Syllabus", @course.syllabus_settings_path, :class => "btn btn-large btn-blue" %>
				</p>
			</div>
		<% end %>
	<% end %>

	<div class="maintainers-container top-space-more">
		<h2>Maintainers</h2>
				<%= render 'lists/inline_list', :items => @course.maintainers, 
											:prioritized => false, :bg_color => :white %>
	</div>

</div>

<%= render 'lists/sectioned_list', :sections => @sections, :sections_have_own_page => false %>

app/views/courses/syllabus_settings.html.erb
<% provide(:title, "Settings for #{@course.name}") %>

<div class="alert alert-white">
	<button class="close" data-dismiss="alert">&times;</button>
	TIP: you can re-order the lessons by dragging the
	&nbsp;
	<strong><span class="color-grey" style="font-size: 15px; line-height: 20px;">&#8942;</span></strong>
	&nbsp;
	icon.
</div>

<div class="row">
	
	<%= render 'courses/settings_nav', :active => :syllabus %>

	<div class="span8 grey-box">
		<h2>Syllabus</h2>

		<% if !@course.sections.any? %>
		<br/>
		<div class="well white-well">
			<p class="medium">
				This syllabus is basically an outline for the course. 
				It is made up of sections, and each section can have one or
				more lessons. Press "add section" below to start making your
				syllabus.
			</p>
		</div>
		<% end %>

		<div class="center new-section-button-container">
			<%= link_to "#", :class => 'new-section-button btn btn-green', 'data-course-id' => @course.id, 'data-url' => sections_url do %>
				<i class="new-section-icon icon-plus"></i>
				<span class="new-section-text">add section</span>
			<% end %>
		</div>

		<div class="top-space sections-for-editable-components">
			<%= render 'lists/sectioned_editable_components_list', :sections => @course.sections, :prioritized => true %>
		</div>

	</div>
</div>